### ISSUE TITLE
Where do I get a JDK 10 AppCDS

### ISSUE THREAD

**Issue by marschall** [simonis/cl4cds#2]
This may no be the right place to ask but maybe you can point me to it.

I'm trying to use AppCDS with ea+43 from http://jdk.java.net/10/ but I get
```
$JAVA_HOME/bin/java -XX:+UseAppCDS -version
Error: Trying to use 'UseAppCDS', but commercial features are not available in this VM.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Adding `-XX:+UnlockCommercialFeatures` does not help

```
$JAVA_HOME/bin/java -XX:+UnlockCommercialFeatures -XX:+UseAppCDS -version
Error: Trying to use 'UnlockCommercialFeatures', but commercial features are not available in this VM.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Building from source on Ubuntu 17.10 fails with:

```
$make images CONF=linux-x86_64-normal-server-fastdebug
Building configuration 'linux-x86_64-normal-server-fastdebug' (matching CONF=linux-x86_64-normal-server-fastdebug)
Building target 'images' in configuration 'linux-x86_64-normal-server-fastdebug'
make[2]: *** No rule to make target 'java.base-libs', needed by 'java.base-interim-jmod'.  Stop.

ERROR: Build failed for target 'images' in configuration 'linux-x86_64-normal-server-fastdebug' (exit code 2)
```

**Comment by simonis** [comment]
You have to download an "OpenJDK build" (instead of taking the "Oracle JDK build") from http://jdk.java.net/10/.

I've no idea why Oracle hasn't put CDS into its "Oracle JDK builds". You should ask them :)

About building: have you called `configure` before calling `make`? The usual way of building OpenJDK is:
```
$ bash configure
$ make images
```

**Comment by marschall** [comment]
> You have to download an "OpenJDK build" (instead of taking the "Oracle JDK build") from http://jdk.java.net/10/.

Thanks.
