### ISSUE TITLE
Error running dump

### ISSUE THREAD

**Issue by philip-ince** [simonis/cl4cds#4]
When running this on MacOS (tomcat 9.0.4 and OpenJDK 10) I get the following error:

An error has occurred while processing class list file /tmp/tomcat.cls 1:39.
Error: negative integers not allowed (-1073738064):
java/lang/Object id: 0x00000007c0000eb0

Any idea what's going on? Thanks!

**Comment by simonis** [comment]
Hi Philip,

thanks for trying cl4cds and yes, I know what’s the problem. HotSpot
internally reads the ID‘s into integers, while the addresses dumped by Xlog
are unsigned 64-bit values. I wanted to fix this for a while but didn‘t
finally managed to do it.

I think for now I can put a workaround into cl4cds by transforming the
addresses into 32-Bit  integers. I‘ll have a look at it tomorrow (Sunday is
family day :)

Regards,
Volker

philip-ince <notifications@github.com> schrieb am So. 25. März 2018 um
15:52:

**Comment by philip-ince** [comment]
Thank you, that would be great. I'd very much like to try the CDS feature now that it's generally available in OpenJDK, but I couldn't believe how few classes are loaded with the default settings! Have you been in touch with the JEP developers about this?

**Comment by simonis** [comment]
Hi Philip,

can you please check if the fix I've just checked in helps with your problem?
If you still get the problem or if you see other errors, can you please run cl4cds with -Dio.simonis.cl4cds.debug=true and attach the output to this issue.

Regards,
Volker
